// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

//  認証するためのinput
type AuthenticateInput struct {
	//  ユーザ名
	Name string `json:"name"`
	//  パスワード
	Password string `json:"password"`
}

//  認証完了後のデータ
type AuthenticatePayload struct {
	//  ユーザ名
	UserName string `json:"userName"`
	//  Json Web Token
	Jwt string `json:"jwt"`
}

//  ToDoを完了するためのInput
type DoneTodo struct {
	//  ToDoのID
	TodoID string `json:"todoID"`
}

//  ToDoを作成するためのinput
type NewTodo struct {
	//  ToDoのテキスト
	Text string `json:"text"`
	//  ユーザ名
	UserName string `json:"userName"`
}

//  ユーザを作成するためのinput
type NewUser struct {
	//  ユニークなユーザ名
	Name string `json:"name"`
	//  パスワード
	Password string `json:"password"`
}

//  ToDo
type Todo struct {
	//  ToDoのID
	TodoID string `json:"todoID"`
	//  ToDoのテキスト
	Text string `json:"text"`
	//  完了したかどうか
	Done bool `json:"done"`
	//  ユーザ
	User *User `json:"user"`
}

//  ユーザ
type User struct {
	//  ユーザ名
	Name string `json:"name"`
}
